const levels=[['Hel & halv',30,'🌱'],['Kvart över/kvart i',15,'🌟'],['Fem minuter',5,'🚀'],['Klockmästare',1,'👑']];let mode='analog',level=0,target=null,locked=false,streak=0;let stars=+(localStorage.clockStars||0),correct=+(localStorage.clockCorrect||0);
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function save(){localStorage.clockStars=stars;localStorage.clockCorrect=correct;$('#stars').textContent=$('#gameStars').textContent=stars;$('#progressText').textContent=correct+' rätt svar';$('#bar').style.width=(correct%10)*10+'%';let left=10-(correct%10);$('#journeyHint').textContent=correct&&correct%10===0?'🏅 Ny medalj upplåst!':left+' rätt till nästa medalj!'}
levels.forEach((l,i)=>{let b=document.createElement('button');b.className='level'+(i===0?' active':'');b.innerHTML=l[2]+' '+(i+1)+'. '+l[0];b.onclick=()=>{$$('.level').forEach(x=>x.classList.remove('active'));b.classList.add('active');level=i};$('#levels').append(b)});
$$('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;start()});
function start(){$('#home').hidden=true;$('#game').hidden=false;$('#levelName').textContent=levels[level][2]+' Nivå '+(level+1);newQ()}
function timeText(h,m){return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')}
function randomTime(){let step=levels[level][1],m=Math.floor(Math.random()*(60/step))*step,h=1+Math.floor(Math.random()*12);return{h,m}}function spokenTime(h,m){let next=h===12?1:h+1;if(m===0)return 'Klockan '+h;if(m===15)return 'Kvart över '+h;if(m===30)return 'Halv '+next;if(m===45)return 'Kvart i '+next;if(m<30)return m+' minuter över '+h;return (60-m)+' minuter i '+next}
function clock(h,m){let el=document.createElement('div');el.className='clock';for(let n=1;n<=12;n++){let s=document.createElement('span');s.className='num';s.textContent=n;s.style.setProperty('--a',n*30+'deg');el.append(s)}let hr=document.createElement('i');hr.className='hand hour';hr.style.transform='translateX(-50%) rotate('+(h*30+m*.5)+'deg)';let mn=document.createElement('i');mn.className='hand minute';mn.style.transform='translateX(-50%) rotate('+(m*6)+'deg)';let d=document.createElement('i');d.className='dot';el.append(hr,mn,d);return el}
function newQ(){locked=false;$('#next').hidden=true;$('#feedback').textContent='';$('#feedback').className='feedback';$('#clockArea').innerHTML='';$('#answers').innerHTML='';$('#streak').textContent=streak;target=randomTime();let show=mode==='mix'?(Math.random()<.5?'analog':'digital'):mode;$('#question').textContent=show==='analog'?'Vad är klockan? 🕐':'Kan du läsa tiden? 🔢';if(show==='analog')$('#clockArea').append(clock(target.h,target.m));else $('#clockArea').innerHTML='<div class="digitalQuestion">🗣️ <span>'+spokenTime(target.h,target.m)+'</span></div>';let vals=[target];while(vals.length<4){let x=randomTime();if(!vals.some(v=>v.h===x.h&&v.m===x.m))vals.push(x)}vals.sort(()=>Math.random()-.5).forEach(v=>{let b=document.createElement('button');b.textContent=timeText(v.h,v.m);b.onclick=()=>answer(v,b);$('#answers').append(b)})}
function celebrate(){let box=$('#confetti');for(let i=0;i<18;i++){let s=document.createElement('span');s.className='confetti';s.textContent=['⭐','✨','🎉','💜','💛'][i%5];s.style.left=Math.random()*100+'%';s.style.animationDelay=Math.random()*.3+'s';box.append(s);setTimeout(()=>s.remove(),1800)}}
function answer(v,b){if(locked)return;locked=true;let good=v.h===target.h&&v.m===target.m;if(good){b.classList.add('correct');streak++;stars++;correct++;save();$('#feedback').className='feedback good pop';$('#feedback').textContent=streak>=3?'🔥 '+streak+' rätt i rad! Du är grym! +1 ⭐':'🎉 JAAA! Helt rätt! +1 ⭐';$('#mascotGame').textContent=streak>=3?'🤩':'🦉';celebrate()}else{b.classList.add('wrong','shake');streak=0;$('#streak').textContent=0;$('#feedback').className='feedback try';$('#feedback').textContent='💪 Bra försök! Rätt svar är '+timeText(target.h,target.m);$$('#answers button').forEach(x=>{if(x.textContent===timeText(target.h,target.m))x.classList.add('correct')});$('#mascotGame').textContent='🙂'}$('#next').hidden=false}
$('#next').onclick=()=>{$('#mascotGame').textContent='🦉';newQ()};$('#back').onclick=()=>{$('#game').hidden=true;$('#home').hidden=false};save();